// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Server$MyNewProject = require("./Server.bs.js");

function parseJson(parser, body) {
  return Server$MyNewProject.$$Response[/* fromOption */5](Curry._1(parser, body), /* Status400 */0, "Invalid JSON format.", undefined, body);
}

exports.parseJson = parseJson;
/* Server-MyNewProject Not a pure module */
