// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Response$MyNewProject = require("./Response.bs.js");

function parseJson(parser, body) {
  return Response$MyNewProject.fromOption(Curry._1(parser, body), /* Status400 */0, "Invalid JSON format.", undefined, body);
}

exports.parseJson = parseJson;
/* Response-MyNewProject Not a pure module */
