// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -845055443,
    "ucs2"
  ],
  /* tuple */[
    -844212943,
    "utf8"
  ],
  /* tuple */[
    -718799473,
    "base64"
  ],
  /* tuple */[
    -714733139,
    "latin1"
  ],
  /* tuple */[
    -317998079,
    "binary"
  ],
  /* tuple */[
    5194459,
    "hex"
  ],
  /* tuple */[
    640502097,
    "ascii"
  ],
  /* tuple */[
    1042356549,
    "utf16le"
  ]
];

function tToJs(param) {
  return Js_mapperRt.binarySearch(8, param, jsMapperConstantArray);
}

function tFromJs(param) {
  return Js_mapperRt.revSearchAssert(8, jsMapperConstantArray, param);
}

exports.tToJs = tToJs;
exports.tFromJs = tFromJs;
/* No side effect */
