// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function toString(enc) {
  switch (enc) {
    case 0 : 
        return "Ascii";
    case 1 : 
        return "Base64";
    case 2 : 
        return "Binary";
    case 3 : 
        return "Hex";
    case 4 : 
        return "Latin1";
    case 5 : 
        return "Ucs2";
    case 6 : 
        return "Utf16le";
    case 7 : 
        return "Utf8";
    
  }
}

exports.toString = toString;
/* No side effect */
