// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Map = require("bs-platform/lib/js/map.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var compare = Caml_obj.caml_compare;

var $$Map$1 = $$Map.Make(/* module */[/* compare */compare]);

exports.$$Map = $$Map$1;
/* Map Not a pure module */
