// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function fromString(code) {
  switch (code) {
    case "CONNECT" : 
        return /* CONNECT */7;
    case "DELETE" : 
        return /* DELETE */4;
    case "GET" : 
        return /* GET */0;
    case "HEAD" : 
        return /* HEAD */5;
    case "OPTION" : 
        return /* OPTION */6;
    case "PATCH" : 
        return /* PATCH */9;
    case "POST" : 
        return /* POST */1;
    case "PUT" : 
        return /* PUT */2;
    case "TRACE" : 
        return /* TRACE */8;
    case "UPDATE" : 
        return /* UPDATE */3;
    default:
      return undefined;
  }
}

exports.fromString = fromString;
/* No side effect */
