// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function toString(mediaType) {
  if (typeof mediaType === "number") {
    switch (mediaType) {
      case 0 : 
          return "application/html";
      case 1 : 
          return "application/json";
      case 2 : 
          return "text/plain";
      case 3 : 
          return "application/xml";
      
    }
  } else {
    return mediaType[0];
  }
}

function fromString(str) {
  switch (str) {
    case "application/html" : 
        return /* Html */0;
    case "application/json" : 
        return /* Json */1;
    case "application/xml" : 
        return /* Xml */3;
    case "text/plain" : 
        return /* Plain */2;
    default:
      return /* Other */[str];
  }
}

exports.toString = toString;
exports.fromString = fromString;
/* No side effect */
