// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Header$Cause = require("./Header.bs.js");

function compose(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

function error($staropt$star, $staropt$star$1, $staropt$star$2) {
  var message = $staropt$star !== undefined ? $staropt$star : "Internal server error";
  var code = $staropt$star$1 !== undefined ? $staropt$star$1 : /* Error500 */34;
  var method_ = $staropt$star$2 !== undefined ? $staropt$star$2 : /* Html */0;
  return /* record */[
          /* code */code,
          /* headers */Header$Cause.$$Map[/* empty */0],
          /* contentType */method_,
          /* body */message,
          /* encoding : Ascii */0
        ];
}

function encode(unencodedBody, response) {
  return /* record */[
          /* code */response[/* code */0],
          /* headers */response[/* headers */1],
          /* contentType */response[/* contentType */2],
          /* body */Curry._1(response[/* body */3], unencodedBody),
          /* encoding */response[/* encoding */4]
        ];
}

function setEncoder(cf, res) {
  var partial_arg = res[/* body */3];
  return /* record */[
          /* code */res[/* code */0],
          /* headers */res[/* headers */1],
          /* contentType */res[/* contentType */2],
          /* body */(function (param) {
              return Curry._1(partial_arg, Curry._1(cf, param));
            }),
          /* encoding */res[/* encoding */4]
        ];
}

function setCode(code, res) {
  return /* record */[
          /* code */code,
          /* headers */res[/* headers */1],
          /* contentType */res[/* contentType */2],
          /* body */res[/* body */3],
          /* encoding */res[/* encoding */4]
        ];
}

function setContentType(mediaType, res) {
  return /* record */[
          /* code */res[/* code */0],
          /* headers */res[/* headers */1],
          /* contentType */mediaType,
          /* body */res[/* body */3],
          /* encoding */res[/* encoding */4]
        ];
}

function json(encoder, res) {
  return setContentType(/* Json */1, setEncoder(encoder, setEncoder((function (prim) {
                        return JSON.stringify(prim);
                      }), res)));
}

exports.compose = compose;
exports.error = error;
exports.encode = encode;
exports.setEncoder = setEncoder;
exports.setCode = setCode;
exports.setContentType = setContentType;
exports.json = json;
/* Header-Cause Not a pure module */
