// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';


function toInt(status) {
  switch (status) {
    case 0 : 
        return 200;
    case 1 : 
        return 201;
    case 2 : 
        return 202;
    case 3 : 
        return 203;
    case 4 : 
        return 204;
    case 5 : 
        return 205;
    case 6 : 
        return 206;
    case 7 : 
        return 300;
    case 8 : 
        return 301;
    case 9 : 
        return 302;
    case 10 : 
        return 303;
    case 11 : 
        return 304;
    case 12 : 
        return 305;
    case 13 : 
        return 307;
    case 14 : 
        return 308;
    case 15 : 
        return 400;
    case 16 : 
        return 401;
    case 17 : 
        return 402;
    case 18 : 
        return 403;
    case 19 : 
        return 404;
    case 20 : 
        return 405;
    case 21 : 
        return 406;
    case 22 : 
        return 407;
    case 23 : 
        return 408;
    case 24 : 
        return 409;
    case 25 : 
        return 410;
    case 26 : 
        return 411;
    case 27 : 
        return 412;
    case 28 : 
        return 413;
    case 29 : 
        return 414;
    case 30 : 
        return 415;
    case 31 : 
        return 416;
    case 32 : 
        return 417;
    case 33 : 
        return 418;
    case 34 : 
        return 500;
    case 35 : 
        return 501;
    case 36 : 
        return 502;
    case 37 : 
        return 503;
    case 38 : 
        return 504;
    case 39 : 
        return 505;
    case 40 : 
        return 509;
    
  }
}

function message(status) {
  switch (status) {
    case 0 : 
        return "OK";
    case 1 : 
        return "Created";
    case 2 : 
        return "Accepted";
    case 3 : 
        return "Non-Authoritative Information";
    case 4 : 
        return "No Content";
    case 5 : 
        return "Reset Content";
    case 6 : 
        return "Partial Content";
    case 7 : 
        return "Multiple Choices";
    case 8 : 
        return "Moved Temporarily";
    case 9 : 
        return "Found";
    case 10 : 
        return "See Other";
    case 11 : 
        return "Not Modified";
    case 12 : 
        return "Use Proxy";
    case 13 : 
        return "Temporary Redirect";
    case 14 : 
        return "Permanent Redirect";
    case 15 : 
        return "Bad Request";
    case 16 : 
        return "Unauthorized";
    case 17 : 
        return "Payment Required";
    case 18 : 
        return "Forbidden";
    case 19 : 
        return "Not Found";
    case 20 : 
        return "Method Not Allowed";
    case 21 : 
        return "Not Acceptable";
    case 22 : 
        return "Proxy Authentication Required";
    case 23 : 
        return "Request Timeout";
    case 24 : 
        return "Conflict";
    case 25 : 
        return "Gone";
    case 26 : 
        return "Length Required";
    case 27 : 
        return "Precondition Failed";
    case 28 : 
        return "Payload Too Large";
    case 29 : 
        return "Request-URI Too Large";
    case 30 : 
        return "Unsupported Media Type";
    case 31 : 
        return "Requested Range Not Satisfied";
    case 32 : 
        return "Expectation Failed";
    case 33 : 
        return "I'm a teapot";
    case 34 : 
        return "Internal Server Error";
    case 35 : 
        return "Not Implemented";
    case 36 : 
        return "Bad Gateway";
    case 37 : 
        return "Service Unavailable";
    case 38 : 
        return "Gateway Timeout";
    case 39 : 
        return "HTTP Version Not Supported";
    case 40 : 
        return "Bandwith Limit Exceeded";
    
  }
}

exports.toInt = toInt;
exports.message = message;
/* No side effect */
