// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Spec$Cause = require("./Spec.bs.js");
var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");
var Server$Cause = require("./Server.bs.js");

function decoder(json) {
  return /* record */[/* name */Json_decode.field("name", Json_decode.string, json)];
}

function postHandler($$int, user) {
  var partial_arg = /* Status200 */0;
  var partial_arg$1 = Server$Cause.Builder[/* sendText */12];
  return (function (param) {
      return partial_arg$1("updated user!", partial_arg, param);
    });
}

var api = Spec$Cause.post(postHandler, Spec$Cause.$great$neg(Spec$Cause.$great$neg(Spec$Cause.is("user"), Spec$Cause.$$int), Spec$Cause.jsonBody(decoder)));

var Spec = /* module */[/* api */api];

var User = /* module */[
  /* decoder */decoder,
  /* postHandler */postHandler,
  /* Spec */Spec
];

var myApp = Spec$Cause.$great$neg(Spec$Cause.is("api"), Spec$Cause.oneOf(/* :: */[
          api,
          /* [] */0
        ]));

var Specification = /* module */[/* myApp */myApp];

exports.User = User;
exports.Specification = Specification;
/* api Not a pure module */
