// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var Server$Cause = require("./Server.bs.js");

function myApp(request) {
  var partial_arg = Server$Cause.Builder[/* sendText */12];
  return (function (eta) {
              var param = undefined;
              var param$1 = eta;
              return partial_arg("Hello", param, param$1);
            })(Server$Cause.Builder[/* start */0](request));
}

exports.myApp = myApp;
/* Server-Cause Not a pure module */
