// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var RawCreateServerJs = require("./rawCreateServer.js");

function tToJs(param) {
  return {
          body: param[/* body */0],
          path: param[/* path */1],
          headers: param[/* headers */2],
          statusCode: param[/* statusCode */3],
          method: param[/* method */4]
        };
}

function tFromJs(param) {
  return /* record */[
          /* body */param.body,
          /* path */param.path,
          /* headers */param.headers,
          /* statusCode */param.statusCode,
          /* method */param.method
        ];
}

var $$Request = /* module */[
  /* tToJs */tToJs,
  /* tFromJs */tFromJs
];

function tToJs$1(param) {
  return {
          bodyString: param[/* bodyString */0],
          bodyBuffer: param[/* bodyBuffer */1],
          headers: param[/* headers */2],
          statusCode: param[/* statusCode */3],
          encoding: param[/* encoding */4],
          statusMessage: param[/* statusMessage */5]
        };
}

function tFromJs$1(param) {
  return /* record */[
          /* bodyString */param.bodyString,
          /* bodyBuffer */param.bodyBuffer,
          /* headers */param.headers,
          /* statusCode */param.statusCode,
          /* encoding */param.encoding,
          /* statusMessage */param.statusMessage
        ];
}

var $$Response = /* module */[
  /* tToJs */tToJs$1,
  /* tFromJs */tFromJs$1
];

function server(prim, prim$1) {
  RawCreateServerJs.rawCreateServer(prim, prim$1);
  return /* () */0;
}

function secureServer(prim, prim$1, prim$2, prim$3) {
  RawCreateServerJs.rawSecureCreateServer(prim, prim$1, prim$2, prim$3);
  return /* () */0;
}

exports.$$Request = $$Request;
exports.$$Response = $$Response;
exports.server = server;
exports.secureServer = secureServer;
/* ./rawCreateServer.js Not a pure module */
